#!/usr/bin/env bash

set -e

mkdir -p ~/.config/karabiner/assets/complex_modifications

mise run jsonnet

cp -v "karabiner/my-rules.json" ~/.config/karabiner/assets/complex_modifications
cp -v "karabiner/my-rules.json" ~/.config/karabiner/karabiner.json
# /Library/Application\ Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli --reload-karabiner-json
